"""Verify the CDK stack synthesizes and contains the expected resources.

Phase 1 deliverable: the Iceberg schema and the stack shape. We assert on
the synthesized CloudFormation template rather than shelling out to the
`cdk` CLI so the test runs hermetically under `uv run pytest`.

If you prefer a CLI smoke check, run (from infra/feature-store):
    uv run cdk synth
"""

from __future__ import annotations

import aws_cdk as cdk
from aws_cdk.assertions import Match, Template

from stacks.feature_store_stack import FeatureStoreStack
from stacks.iceberg_schemas import FEATURE_GROUP_SCHEMAS


def _synth(tenant_id: str = "aircanada") -> Template:
    app = cdk.App()
    stack = FeatureStoreStack(app, f"TraxIO-FeatureStore-{tenant_id}", tenant_id=tenant_id)
    return Template.from_stack(stack)


def test_stack_has_tenant_kms_key():
    tpl = _synth()
    tpl.resource_count_is("AWS::KMS::Key", 1)
    tpl.has_resource_properties(
        "AWS::KMS::Alias",
        {"AliasName": Match.string_like_regexp(r"alias/trax-io/.+")},
    )


def test_stack_has_two_s3_buckets_kms_encrypted():
    tpl = _synth()
    buckets = tpl.find_resources("AWS::S3::Bucket")
    assert len(buckets) == 2, f"expected landing + lake buckets, got {len(buckets)}"


def test_stack_has_one_glue_database():
    _synth().resource_count_is("AWS::Glue::Database", 1)


def test_stack_has_one_iceberg_table_per_feature_group():
    tpl = _synth()
    tables = tpl.find_resources("AWS::Glue::Table")
    assert len(tables) == len(FEATURE_GROUP_SCHEMAS), (
        f"expected {len(FEATURE_GROUP_SCHEMAS)} Glue tables (one per feature "
        f"group), got {len(tables)}"
    )


def test_every_iceberg_table_is_partitioned_by_tenant_and_extract_date():
    tpl = _synth()
    tables = tpl.find_resources("AWS::Glue::Table")
    for logical_id, resource in tables.items():
        partition_keys = resource["Properties"]["TableInput"]["PartitionKeys"]
        names = [k["Name"] for k in partition_keys]
        assert names == ["tenant_id", "extract_date"], (
            f"{logical_id} partitioning = {names}, expected ['tenant_id', 'extract_date']"
        )


def test_every_iceberg_table_declares_format_version_2():
    tpl = _synth()
    tables = tpl.find_resources("AWS::Glue::Table")
    for logical_id, resource in tables.items():
        params = resource["Properties"]["TableInput"]["Parameters"]
        assert params.get("table_type") == "ICEBERG", (
            f"{logical_id} is not flagged as Iceberg"
        )
        assert params.get("format-version") == "2", (
            f"{logical_id} missing format-version=2 (time-travel required for SOC 2)"
        )


def test_online_dynamodb_table_is_tenant_keyed():
    tpl = _synth()
    tpl.resource_count_is("AWS::DynamoDB::Table", 1)
    tpl.has_resource_properties(
        "AWS::DynamoDB::Table",
        {
            "KeySchema": [
                {"AttributeName": "tenant_id", "KeyType": "HASH"},
                {"AttributeName": "pn_location", "KeyType": "RANGE"},
            ],
            "SSESpecification": {"SSEEnabled": True, "SSEType": "KMS"},
            "PointInTimeRecoverySpecification": {"PointInTimeRecoveryEnabled": True},
        },
    )


def test_demand_history_glue_job_is_synthesized():
    tpl = _synth()
    jobs = tpl.find_resources("AWS::Glue::Job")
    assert len(jobs) == 1, f"expected 1 Glue job (demand_history), got {len(jobs)}"
    (_, job), = jobs.items()
    props = job["Properties"]
    assert props["GlueVersion"] == "4.0"
    assert props["WorkerType"] == "G.1X"
    assert props["NumberOfWorkers"] == 2
    assert props["Command"]["Name"] == "glueetl"
    assert props["Command"]["PythonVersion"] == "3"
    # Script location is an S3 URI generated by the CDK asset system.
    script_loc = props["Command"]["ScriptLocation"]
    # CDK renders it as a joined Fn::Sub/Fn::Join reference to the assets bucket.
    # We just assert it's present and references s3.
    assert script_loc, "ScriptLocation must be set"


def test_glue_role_scoped_to_tenant_kms():
    tpl = _synth()
    policies = tpl.find_resources("AWS::IAM::Policy")
    # At least one policy must grant kms:Decrypt + kms:GenerateDataKey scoped
    # to the tenant KMS key ARN (a Fn::GetAtt reference to the CMK), not "*".
    found = False
    for _, pol in policies.items():
        for stmt in pol["Properties"]["PolicyDocument"]["Statement"]:
            actions = stmt.get("Action", [])
            if isinstance(actions, str):
                actions = [actions]
            if "kms:Decrypt" in actions and "kms:GenerateDataKey" in actions:
                resource = stmt.get("Resource")
                # Must NOT be "*".
                assert resource != "*", "KMS policy must be resource-scoped"
                # Must reference the CMK (Fn::GetAtt TenantCmk... Arn).
                rendered = str(resource)
                assert "TenantCmk" in rendered, (
                    f"KMS policy should reference tenant CMK, got {rendered!r}"
                )
                found = True
    assert found, "no KMS policy statement found on the Glue role"


def test_glue_job_reads_landing_writes_lake():
    tpl = _synth()
    policies = tpl.find_resources("AWS::IAM::Policy")
    saw_landing_read = False
    saw_lake_write = False
    for _, pol in policies.items():
        stmts = pol["Properties"]["PolicyDocument"]["Statement"]
        rendered = str(stmts)
        # CDK names bucket resources by logical id.
        if "LandingBucket" in rendered and ("s3:GetObject" in rendered):
            saw_landing_read = True
        if "LakeBucket" in rendered and (
            "s3:PutObject" in rendered or "s3:DeleteObject" in rendered
        ):
            saw_lake_write = True
    assert saw_landing_read, "Glue role missing landing-bucket read grant"
    assert saw_lake_write, "Glue role missing lake-bucket write grant"


def test_project_tag_is_applied():
    tpl = _synth()
    # Every Glue table should carry Project=TraxIO via stack-level tag propagation.
    # Glue tables don't surface tags in the same shape as other resources, so we
    # assert on the bucket tag set instead.
    buckets = tpl.find_resources("AWS::S3::Bucket")
    for logical_id, resource in buckets.items():
        tags = resource["Properties"].get("Tags", [])
        tag_map = {t["Key"]: t["Value"] for t in tags}
        assert tag_map.get("Project") == "TraxIO", f"{logical_id} missing Project=TraxIO"
        assert tag_map.get("TenantId") == "aircanada", f"{logical_id} missing TenantId tag"
