CREATE SEQUENCE WRITEBACK_LEDGER_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE WRITEBACK_LEDGER (
    ID               NUMBER(19)     NOT NULL PRIMARY KEY,
    IDEMPOTENCY_KEY  VARCHAR2(200)  NOT NULL,
    TENANT_ID        VARCHAR2(64)   NOT NULL,
    RUN_ID           VARCHAR2(128),
    ROW_ID           NUMBER(19),
    PROVENANCE_ID    VARCHAR2(128),
    PN               VARCHAR2(100)  NOT NULL,
    LOCATION         VARCHAR2(40)   NOT NULL,
    SOURCE           VARCHAR2(64),
    TIER             NUMBER(2),
    APPROVER         VARCHAR2(128),
    PRINCIPAL        VARCHAR2(128)  NOT NULL,
    AGENT_VERSION    VARCHAR2(64)   NOT NULL,
    OUTCOME          VARCHAR2(32)   NOT NULL,
    VERSION          NUMBER(10),
    PARENT_VERSION   NUMBER(10),
    OLD_VALUES_JSON  CLOB,
    NEW_VALUES_JSON  CLOB,
    MESSAGE          VARCHAR2(2000),
    CREATED_AT       TIMESTAMP      NOT NULL,
    CONSTRAINT UQ_WRITEBACK_IDEMPOTENCY UNIQUE (TENANT_ID, IDEMPOTENCY_KEY)
);

ALTER TABLE WRITEBACK_LEDGER ADD CONSTRAINT UQ_WRITEBACK_KEY_VERSION UNIQUE (TENANT_ID, PN, LOCATION, VERSION);
